- name: turntouch
  mac: E2:35:4F:B2:6C:D3
  default_action: echo
  buttons:
    north_press:
      type: echo
      command: echo "Hello North"
    north_double:
      type: bash
      command: echo "Double North"
    battery_10:
      type: bash
      command: echo "Battery Low!"
